prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false 
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    
    scrape_interval: 30s
    retention: 7d

grafana:
  #password hardwired because there is no assignment requirement for secrets
  adminPassword: cs312
  #wire in the custom dashboard
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
 
  persistence:
    enabled: true
    size: 1Gi

