{
 "title": "Minecraft customized Dashboard",
 "description": "Minecraft customized dashboard with minecraft relative statistics including player count and memory usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Minecraft server statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Player online count",
   "type": "stat",
   "description": "The amount of players currently online the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minecraft Server Response time",
   "type": "timeseries",
   "description": "The response time of the server, can be used to indicate lag. If response time is contextually very high and abnormal, then the server may be experiencing large amounts of lag",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "description": "The amount of pod restarts, a high restart value can issue crash looping and may need manual intervention.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\"minecraft.*\", pod!~\".*backup.*\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minecraft pod readiness",
   "type": "stat",
   "description": "1 means the pod is ready\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"default\", pod=~\"minecraft.*\", pod!~\".*backup.*\",condition=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod memory usage versus max memory usage",
   "type": "timeseries",
   "description": "Yellow is the maximum memory usage for the pod, the yellow indicates remaining headroom and green indicates actual usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"default\", pod=~\"minecraft.*\", pod!~\".*backup.*\", container=\"minecraft\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"default\", resource=\"memory\", container=\"minecraft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Machine statistics and heatlh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Disk usage %",
   "type": "bargauge",
   "description": "The amount of disk usage the machine is currently at, if the disk begins to get to full it may cause errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage %",
   "type": "gauge",
   "description": "The amount of memory the node is currently using.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "gauge",
   "description": "The current percentage of CPU usage of the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}